### ISSUE TITLE
Добавить панель фильтрации

### ISSUE THREAD

**Issue by KekStroke** [InnoTableTennis/frontend#18]
Переместить панель администратора влево (оставить сверху для мобильной версии, сепаратор убрать)
Поменять дизайн панели (для шрифтов и цветов использовать переменные)
Добавить ещё одну панель для фильтрации и поставить ее на место панели админимтратора
По нажатию на кнопку менять компоненты (панели)
Добавить функционал поиска и фильтрации через fetch запросы на бэкенд
Продублировать на все страницы которые нуждаются в данном функционале
Проверить, что при вводе фильтров и последующем добавлении игроков, фильтры сохраняются.
Фильтры также должны сохраняться при переходе на другие страницы (можно сделать с помощью сторов)

**Comment by KekStroke** [comment]
Дизайн должен соответствовать дизайну в figma. Мелкими неточностями, связанными с сильным усложнением кодовой базы, можно пренебречь

**Comment by Zaurall** [comment]
Переделать форму score в matches sort странице
done

**Comment by Zaurall** [comment]
Доделать toggle checkbox на страницах tournaments, pages, players
done

**Comment by Zaurall** [comment]
Сделать event types в sort and filter match, player, tournament
done

**Comment by Zaurall** [comment]
Поправить layout таблиц
done

**Comment by Zaurall** [comment]
Вывод ошибки из-за формата score
done

**Comment by Zaurall** [comment]
Сделать validation input
